### ISSUE TITLE
Add german country names and swiss local names

### ISSUE THREAD

**Issue by joshuabeny1999** [biter777/countries#17]
I did some work and created following pull request: #16 

Hope it helps.

**Comment by biter777** [comment]
Added
Thnx :)

**Comment by joshuabeny1999** [comment]
Hi @biter777 

Could you also create a new tag (1.3.2 for example), so it could be used in the go projects? There you need to add the version in the go.mod and this is normally the tag.

Thanks,
Joshua

**Comment by biter777** [comment]
Of course. 
Done! 

U r welcome!

**Comment by joshuabeny1999** [comment]
Thanks :)
