### ISSUE TITLE
United States currency maps to USN rather than USD

### ISSUE THREAD

**Issue by Woody1193** [biter777/countries#20]
This may be a bit of a nitpick but, according to my understand, the United States has two currency codes associated with it: US dollar (USD) and US dollar, next day (USN). Why is it that calling `countries.UnitedStatesOfAmerica.Info().Currency.Alpha()` returns `USN` rather than `USD` when `USD` would be the more idiomatic usage? My use case for this code-base is primarily getting the 2-character country code and currency combinations associated with each for internationalization purposes but this doesn't seem fit-for-purpose. Perhaps split the US entry into two entries would fix this issue?

**Note:** I can get around this by taking the country code and doing `countries.CurrencyCode(code)` to get the proper code and if this is the intended usage when there is a collision then I would appreciate a function that does that explicitly.

**Comment by tommy-muehle** [comment]
The same goes for Switzerland where CHE (WIR euro, which isn't tradeable) is returned instead of CHF.

@Woody1193 
We switched the logic. So we check if CHF returns CH as country code. You can do the same with USD for US.
This approach also is valid if someone would use USN then.
