### ISSUE TITLE
How to convert Alpha3 to Alpha2?

### ISSUE THREAD

**Issue by m1d1** [biter777/countries#25]
Is there a way to convert ISO-3166-1 alpha3 country codes to alpha2? I.e. "AUT" to "AT".

I'm using the no longer maintained project 

https://github.com/launchdarkly/go-country-codes

which has the GetByAlpha3() method, which I'm missing here. 

Thanks.

**Comment by m1d1** [comment]
I found that ByName() is taking the alpha3 as argument, thanks!

**Comment by biter777** [comment]
U r welcome! :)
