### ISSUE TITLE
Czech Republic or Czechia?

### ISSUE THREAD

**Issue by imprint75** [biter777/countries#33]
Thanks for your work on this! 

We're noticing that `countries.ByName("CZE")` is returning Czech Republic [here](https://github.com/biter777/countries/blob/7b8b64334ecacdea9fd9dbd2d115a1f78bdc70a4/countries.go#L270-L271). The general pattern seem to be that we return the `name` as opposed to `official_name` from [here](https://github.com/biter777/countries/blob/7b8b64334ecacdea9fd9dbd2d115a1f78bdc70a4/data/iso-codes/data_iso_3166-1.json) in which case it seems like it should be Czechia, unless I'm missing something. Happy to submit a pr to resolve if this is not intentional.

**Comment by biter777** [comment]
Make a PR pls.
U r welcome! :)

**Comment by biter777** [comment]
Fixed
