### ISSUE TITLE
Sudan Country Code is Incorrect

### ISSUE THREAD

**Issue by SamuelCarroll** [biter777/countries#35]
The following files have the Sudan code set to 736
https://github.com/biter777/countries/blob/7b8b64334ecacdea9fd9dbd2d115a1f78bdc70a4/countries.go#L554
https://github.com/biter777/countries/blame/272527eec1cf53264796c3aaa1047afe2cee775b/countriesconst.go#L425

Per the ISO standard this should be 729
https://github.com/biter777/countries/blob/7b8b64334ecacdea9fd9dbd2d115a1f78bdc70a4/data/iso-codes/data_iso_3166-1.json#L1292
https://www.iso.org/obp/ui/#iso:code:3166:SD

**Comment by biter777** [comment]
Sudan code updated!
Thx!
