### ISSUE TITLE
Change in module name leads to inaccessible releases. 

### ISSUE THREAD

**Issue by marvinkite** [biter777/countries#36]
How shell I reference the latest releases from external project?

In this repo the module name was changed https://github.com/biter777/countries/commit/ea149524624519c1d92957319a223c661b6582bf but the other repository https://github.com/royshahaf/countries last commit is from February and there is no way to reference the recent changes any way.

in go.mod 

```
require (
	github.com/biter777/countries v1.3.4 <- This is the last working version
	github.com/royshahaf/countries v1.5.1 <- This repo has only github.com/royshahaf/countries v1.3.7

```

Now Go can't find the right module and the right repository.

```
go: github.com/biter777/countries@v1.5.1: parsing go.mod:
        module declares its path as: github.com/royshahaf/countries
                but was required as: github.com/biter777/countries
```

The two only working version now are
* github.com/biter777/countries v1.3.4
* github.com/royshahaf/countries v1.3.7

Either fix the module names or please update the repository so the v1.5.x can be referenced from externally.

**Comment by biter777** [comment]
Done
