### ISSUE TITLE
Fix Brazil currency code

### ISSUE THREAD

**Issue by CarinaPetravicius** [biter777/countries#40]
I like to use this lib, soo when I started to test for Brazil, I got a problem because the lib just accept the code 76 for Brazil currency. But as we can see at https://pt.wikipedia.org/wiki/ISO_4217, the code 76 is for a very old Brazil currency named as Cruzeiro that is no longer valid since 30 years ago. The correct Brazil code is 986 for currency named as Real.

I created a PR for this fix, I would like if the maintainer could review :) 
https://github.com/biter777/countries/pull/39

**Comment by biter777** [comment]
Fixed
