### ISSUE TITLE
more names to identify country names

### ISSUE THREAD

**Issue by Deepanshusuman** [biter777/countries#41]
MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF => North Macedonia
VENEZUELA, BOLIVARIAN REPUBLIC OF => Venezuela
MOLDOVA, REPUBLIC OF => Moldova
TAIWAN, PROVINCE OF CHINA =>Taiwan
PALESTINIAN TERRITORY, OCCUPIED => Palestine

**Comment by biter777** [comment]
Added
