### ISSUE TITLE
`SubdivisionCode` does not implement sql.Scanner and driver.Valuer interfaces

### ISSUE THREAD

**Issue by Sophie1142** [biter777/countries#43]
First of all, thank you for this amazing package! You've saved me a TON of work.

One call out I have is, this package doesn't seem to implement the `database/sql/driver.Valuer` and `database/sql/driver.Valuer` interfaces for `SubdivisionCode`.

How I arrived at this conclusion:
I have an API that takes in POST requests from the client, marshals it into a Go struct, then uses Gorm to store that struct model in a Postgres DB.
The struct has a field of type `countries.SubdivisionCode`, and the package is able to correctly unmarshal it into the struct as a string (i.e. "US-MA" --> "Massachusetts"). It also correctly inserts it into the DB as "Massachusetts." However, when I select that record from the DB and unmarshal it into a Go struct, the subdivision code field reads as "Unknown".

**✅ POST request:**
<img width="621" alt="image" src="https://user-images.githubusercontent.com/43194894/208169075-a153dc24-14da-43d0-81ae-9d57ad3abcea.png">

**✅ Unmarshal the Request Body with Fiber into a Struct:**
<img width="614" alt="image" src="https://user-images.githubusercontent.com/43194894/208169199-a68b935c-4147-4c81-9dda-ef2361a5cc4c.png">

**✅ Insert Into the DB:**
<img width="237" alt="image" src="https://user-images.githubusercontent.com/43194894/208169362-4a343bf7-471c-40b7-97d5-80c490856c11.png">

**❌  Select that Record from DB:** Now the field shows up as Unknown.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/43194894/208169458-745bc2c5-9deb-4d51-a641-de648d158e67.png">

On a related note, what function is causing "US-MA" to be read in as "Massachusetts" and when is that function called? Is there a way to insert it into the DB as a "US-MA"?

EDIT:
Using `fmt.Printf("%+v")` printed the field as `"Massachusetts"` (I'm guessing the package uses the String() method to do so), but when I just use `fmt.Printf("%#v")`, it outputs as `"US-MA".` Still, how is it getting inserted into the DB as "Massachusetts" when it doesn't have an explicit driver.Valuer function?

**Comment by biter777** [comment]
Please show your code (insert to db, read from db)

**Comment by biter777** [comment]
@Sophie1142 pls reopen issue, if still relevant
