### ISSUE TITLE
Official Turkish country name not recognised

### ISSUE THREAD

**Issue by djames-bloom** [biter777/countries#49]
As of December 2021, Turkey was renamed to Türkiye (full, Republic of Türkiye). This change has been recognised and adopted by the UN, WTO and NATO as of July 2022 [[cite]](https://www.theguardian.com/world/2022/jun/03/turkey-changes-name-to-turkiye-as-other-name-is-for-the-birds) [[cite]](https://www.euronews.com/my-europe/2022/06/28/turkey-is-now-turkiye-what-other-countries-have-changed-their-name) and US State Department as of January 2023 [[cite]](https://www.npr.org/2023/01/08/1147704945/the-state-department-will-begin-spelling-turkey-as-turkiye).

It would be great if the package could be updated to reflect this change.

Current name resolution
| Resolves | Name |
|:---:|---|
| ✅ | Turkey |
|  | Republic of Türkiye |
| | Türkiye |

**Comment by biter777** [comment]
Updated
