### ISSUE TITLE
Add Kosovo with temporary country code

### ISSUE THREAD

**Issue by benja-M-1** [biter777/countries#5]
Hi 👋

I suggest to add the temporary country codes for Kosovo. There is no ISO code yet but some organisations already use XK and XKX.

I've added it in my fork: https://github.com/benja-M-1/countries/tree/patch-kosovo.
I can submit a PR if you are ok with that. (unfortunately there is an issue with the formatting and git was unable to make a correct diff)

**Comment by biter777** [comment]
That's a good idea! Submit a PR please.

**Comment by biter777** [comment]
Kosovo added.
