### ISSUE TITLE
Incl Alternate Code for Kosovo

### ISSUE THREAD

**Issue by hfkang** [biter777/countries#69]
hello,

Building off an earlier issue (https://github.com/biter777/countries/issues/5),
Apple denotes Kosovo as `XKS` instead of using `XKX` in its In-App-Purchase libraries; would it be possible to include that in the country list? 
I can create a PR from my fork: https://github.com/biter777/countries/compare/master...hfkang:countries:AddKosovo_XKS

thanks!

**Comment by biter777** [comment]
Ok, make PR

**Comment by hfkang** [comment]
@biter777 created PR https://github.com/biter777/countries/pull/70

**Comment by biter777** [comment]
Done!

**Comment by hfkang** [comment]
thank you!
