### ISSUE TITLE
Rename "острова Туркс и Кайкос" to "острова Теркс и Кайкос"

### ISSUE THREAD

**Issue by Kitichka** [biter777/countries#71]
There is a typo in Islands naming: 
1. Open https://github.com/biter777/countries/blob/master/countries.go
**Actual result**: String path 1131
case 796:
		return "острова Туркс и Кайкос"
**Expected result**: case 796:
		return "острова Теркс и Кайкос"
		
Details in [wiki](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%80%D0%BA%D1%81_%D0%B8_%D0%9A%D0%B0%D0%B9%D0%BA%D0%BE%D1%81)

**Comment by biter777** [comment]
Done
Thnx
